# Generated by Django 6.0.6 on 2026-07-24 10:01

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Category name (e.g., Food, Salary, Rent)', max_length=256)),
                ('type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], default='income', max_length=10)),
                ('icon', models.CharField(blank=True, help_text='FontAwesome or emoji icon', max_length=50, null=True)),
                ('color', models.CharField(default='#6C757D', help_text='Hex color code (e.g., #FF6B6B)', max_length=7)),
                ('is_archived', models.BooleanField(default=True, help_text="Archived categories won't appear in dropdowns")),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['type', 'name'],
                'unique_together': {('user', 'name', 'type')},
            },
        ),
        migrations.CreateModel(
            name='TransactionModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('amount', models.BigIntegerField(default=0)),
                ('type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], default='income', max_length=20)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('month', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='finance.categorymodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['user', 'date'], name='finance_tra_user_id_bff451_idx'), models.Index(fields=['user', 'category'], name='finance_tra_user_id_c4bfbc_idx')],
            },
        ),
    ]
